### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ryuken** [pusher/pusher-test#7]
Why does it connect with ws:// when SSL is on
When SSL is off it connects with wss://

Shouldn't it be the other way around?

**Comment by leesio** [comment]
Just tried this on test.pusher.com and it connects with `wss://` when ssl is enabled and `ws://` when ssl is disabled for me.
It's a little confusing though as when SSL is *enabled* the button displays "SSL off" to describe the state mutation caused by pressing the button. Perhaps we should update the button label to better reflect this distinction.

**Comment by ryuken** [comment]
Ah yeah i guess that was the confusing part sorry lol
